version: "3"
services:
#---------------------------------------------------------------------#
#                Portainer - Container Management                     #
#---------------------------------------------------------------------#
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy
    labels:
      - "traefik.http.routers.portainer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"


#---------------------------------------------------------------------#
#           Prometheus - Logging your docker services                 #
#---------------------------------------------------------------------#
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/prometheus
    ports: 
      - 9090:9090
    networks:
      - proxy
        # - monitoring
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`${DOMAINPROMETHEUS}`)"
      - "traefik.http.routers.prometheus.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/passwd"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"

#---------------------------------------------------------------------#
#                     Grafana - Visualization                         #
#---------------------------------------------------------------------#
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - proxy
    labels:
      - "traefik.http.routers.grafana.rule=Host(`${DOMAINGRAFANA}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"
#---------------------------------------------------------------------#
#                        Dozzle - Log Viewer                          #
#---------------------------------------------------------------------#
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:9999
    networks:
      - proxy
    labels:
      - "traefik.http.routers.dozzle.rule=Host(`${DOMAINDOZZLE}`)"
      - "traefik.http.routers.dozzle.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/passwd"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"

volumes:
  portainer_data:
  prometheus-volume:
  grafana-data:
networks:
  proxy:
    external: true
    name: traefik
